ALTER TABLE RESERVERING DROP FOREIGN KEY FK_RESERVERING_CONTACTPERSOON_ID
ALTER TABLE BEZOEK_PERSOON DROP FOREIGN KEY FK_BEZOEK_PERSOON_gasten_ID
ALTER TABLE BEZOEK_PERSOON DROP FOREIGN KEY FK_BEZOEK_PERSOON_Bezoek_ID
DROP TABLE BEZOEK
DROP TABLE RESERVERING
DROP TABLE PERSOON
DROP TABLE TAFEL
DROP TABLE BEZOEK_PERSOON
